[package]
name = "app"
version = "1.1.0"
description = "NEURODECK — AI Terminal Interface for Steam Deck"
authors = ["khaoticdev62"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.2", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.2", features = [] }
tauri-plugin-log = "2"
reqwest = { version = "0.12", features = ["json", "stream", "blocking"] }
futures-util = "0.3"
toml = "0.8"
tokio = { version = "1", features = ["full"] }
base64 = "0.22"
async-stream = "0.3"
chrono = { version = "0.4", features = ["serde"] }
lazy_static = "1.5"
regex = "1"
mlua = { version = "0.9", features = ["lua54", "vendored", "send"] }
portable-pty = "0.8"
tokio-util = { version = "0.7", features = ["codec"] }
rand = "0.8"
anyhow = "1.0"
suppaftp = "6"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
tracing-appender = "0.2.5"
neurodeck_core = { version = "0.1.0", path = "../core" }
neurodeck_infrastructure = { version = "0.1.0", path = "../infrastructure" }
mdns-sd = "0.19.2"
tar = "0.4.40"
tonic = "0.11"
axum = { version = "0.7", features = ["ws"] }
tower = "0.4"
walkdir = "2.3"


