name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pnpm build && cargo build --workspace --release
      - run: pnpm package:linux
      - run: pnpm release:checksums
      - run: pnpm release:verify
