/** Single source of truth for IPC channel names — main, preload, and renderer all import this rather than hand-typing strings. */
export const IPC_CHANNELS = {
  workspaceList: 'workspace.list',
  workspaceCreate: 'workspace.create',
  workspaceRemove: 'workspace.remove',
  workspacePickFolder: 'workspace.pickFolder',
  fileList: 'file.list',
  fileRead: 'file.read',
  gitStatus: 'git.status',
  gitDiff: 'git.diff',
  gitStage: 'git.stage',
  gitUnstage: 'git.unstage',
  gitCommit: 'git.commit',
  gitBranches: 'git.branches',
  gitCheckout: 'git.checkout',
  gitLog: 'git.log',
  gitRemotes: 'git.remotes',
  gitFetch: 'git.fetch',
  gitPull: 'git.pull',
  gitPush: 'git.push',
  gitStashSave: 'git.stashSave',
  gitStashList: 'git.stashList',
  gitStashPop: 'git.stashPop',
  terminalCreate: 'terminal.create',
  terminalList: 'terminal.list',
  terminalSnapshot: 'terminal.snapshot',
  terminalWrite: 'terminal.write',
  terminalResize: 'terminal.resize',
  terminalTerminate: 'terminal.terminate',
  terminalData: 'terminal.data',
  terminalExit: 'terminal.exit'
} as const
