// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An `Intent` represents a typed command originating from the frontend.
 * It replaces unstructured Tauri commands.
 */
export type Intent =
  | { type: "StartTerminal"; payload: { id: string; shell: string | null } }
  | { type: "KillTerminal"; payload: { id: string } }
  | { type: "TerminalInput"; payload: { id: string; data: string } }
  | { type: "TerminalResize"; payload: { id: string; cols: number; rows: number } }
  | { type: "SendMessage"; payload: { text: string; persona: string } }
  | { type: "CancelGeneration" }
  | { type: "RequestGameState" };
