import type { TerminalSafetyLevel } from "./terminalSafetyTypes";

export type TerminalCwdStrategy = "home" | "workspaceRoot" | "lastSession" | "projectRoot" | "custom";

export type TerminalProfile = {
  id: string;
  name: string;
  description: string;
  platform: "linux" | "windows" | "macos" | "steamdeck" | "cross_platform";
  shellPath: string;
  shellArgs: string[];
  cwdStrategy: TerminalCwdStrategy;
  envPolicy: {
    inheritSafeEnv: boolean;
    allowedEnvKeys: string[];
    blockedEnvKeys: string[];
    injectProjectEnv: boolean;
  };
  safety: {
    readOnlyMode: boolean;
    allowDestructiveCommands: boolean;
    requireConfirmationForDangerousCommands: boolean;
    allowNetworkCommands: boolean;
    allowPackageInstall: boolean;
    allowVpnCommands: boolean;
  };
  aiAssist: {
    enabled: boolean;
    allowCommandSuggestions: boolean;
    allowCommandExplanation: boolean;
    allowAutoFixSuggestions: boolean;
    autoExecuteAllowed: false;
  };
  productionReady: boolean;
};

export type TerminalProfileAvailability = TerminalProfile & {
  shellAvailable: boolean;
  shellStatus: "ready" | "missing_shell_binary" | "unknown";
  detectedPath?: string | null;
  shellSafety: TerminalSafetyLevel;
};

function createProfile(profile: TerminalProfile): TerminalProfile {
  return profile;
}

export const TERMINAL_PROFILES: TerminalProfile[] = [
  createProfile({
    id: "linux-bash",
    name: "Linux Bash",
    description: "Standard Linux Bash login shell for general development workflows.",
    platform: "linux",
    shellPath: "/bin/bash",
    shellArgs: ["--login"],
    cwdStrategy: "workspaceRoot",
    envPolicy: {
      inheritSafeEnv: true,
      allowedEnvKeys: ["HOME", "PATH", "TERM", "LANG", "LC_ALL", "DISPLAY", "XDG_RUNTIME_DIR"],
      blockedEnvKeys: ["GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
      injectProjectEnv: true,
    },
    safety: {
      readOnlyMode: false,
      allowDestructiveCommands: true,
      requireConfirmationForDangerousCommands: true,
      allowNetworkCommands: true,
      allowPackageInstall: true,
      allowVpnCommands: true,
    },
    aiAssist: { enabled: true, allowCommandSuggestions: true, allowCommandExplanation: true, allowAutoFixSuggestions: true, autoExecuteAllowed: false },
    productionReady: true,
  }),
  createProfile({
    id: "linux-zsh",
    name: "Linux Zsh",
    description: "Zsh login shell for Linux with Oh-My-Zsh and plugin support.",
    platform: "linux",
    shellPath: "/bin/zsh",
    shellArgs: ["--login"],
    cwdStrategy: "workspaceRoot",
    envPolicy: {
      inheritSafeEnv: true,
      allowedEnvKeys: ["HOME", "PATH", "TERM", "LANG", "LC_ALL", "DISPLAY", "XDG_RUNTIME_DIR"],
      blockedEnvKeys: ["GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
      injectProjectEnv: true,
    },
    safety: {
      readOnlyMode: false,
      allowDestructiveCommands: true,
      requireConfirmationForDangerousCommands: true,
      allowNetworkCommands: true,
      allowPackageInstall: true,
      allowVpnCommands: true,
    },
    aiAssist: { enabled: true, allowCommandSuggestions: true, allowCommandExplanation: true, allowAutoFixSuggestions: true, autoExecuteAllowed: false },
    productionReady: true,
  }),
  createProfile({
    id: "fish-shell",
    name: "Fish Shell",
    description: "Friendly interactive shell with smart completions and syntax highlighting.",
    platform: "linux",
    shellPath: "/usr/bin/fish",
    shellArgs: ["--login"],
    cwdStrategy: "workspaceRoot",
    envPolicy: {
      inheritSafeEnv: true,
      allowedEnvKeys: ["HOME", "PATH", "TERM", "LANG", "LC_ALL", "DISPLAY", "XDG_RUNTIME_DIR"],
      blockedEnvKeys: ["GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
      injectProjectEnv: true,
    },
    safety: {
      readOnlyMode: false,
      allowDestructiveCommands: true,
      requireConfirmationForDangerousCommands: true,
      allowNetworkCommands: true,
      allowPackageInstall: true,
      allowVpnCommands: false,
    },
    aiAssist: { enabled: true, allowCommandSuggestions: true, allowCommandExplanation: true, allowAutoFixSuggestions: true, autoExecuteAllowed: false },
    productionReady: true,
  }),
  createProfile({
    id: "macos-zsh",
    name: "macOS Zsh",
    description: "Default macOS system shell. Z shell with macOS environment and Homebrew paths.",
    platform: "macos",
    shellPath: "/bin/zsh",
    shellArgs: ["--login"],
    cwdStrategy: "workspaceRoot",
    envPolicy: {
      inheritSafeEnv: true,
      allowedEnvKeys: ["HOME", "PATH", "TERM", "LANG", "LC_ALL", "TMPDIR", "USER", "LOGNAME"],
      blockedEnvKeys: ["GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
      injectProjectEnv: true,
    },
    safety: {
      readOnlyMode: false,
      allowDestructiveCommands: true,
      requireConfirmationForDangerousCommands: true,
      allowNetworkCommands: true,
      allowPackageInstall: true,
      allowVpnCommands: true,
    },
    aiAssist: { enabled: true, allowCommandSuggestions: true, allowCommandExplanation: true, allowAutoFixSuggestions: true, autoExecuteAllowed: false },
    productionReady: true,
  }),
  createProfile({
    id: "macos-bash",
    name: "macOS Bash",
    description: "macOS Bash login shell. Useful for legacy scripts and compatibility with bash 3.2.",
    platform: "macos",
    shellPath: "/bin/bash",
    shellArgs: ["--login"],
    cwdStrategy: "workspaceRoot",
    envPolicy: {
      inheritSafeEnv: true,
      allowedEnvKeys: ["HOME", "PATH", "TERM", "LANG", "LC_ALL", "TMPDIR", "USER", "LOGNAME"],
      blockedEnvKeys: ["GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
      injectProjectEnv: true,
    },
    safety: {
      readOnlyMode: false,
      allowDestructiveCommands: true,
      requireConfirmationForDangerousCommands: true,
      allowNetworkCommands: true,
      allowPackageInstall: true,
      allowVpnCommands: true,
    },
    aiAssist: { enabled: true, allowCommandSuggestions: true, allowCommandExplanation: true, allowAutoFixSuggestions: true, autoExecuteAllowed: false },
    productionReady: true,
  }),
  createProfile({
    id: "wsl-bash",
    name: "WSL Bash",
    description: "Windows Subsystem for Linux Bash. Runs a full Linux environment inside Windows.",
    platform: "windows",
    shellPath: "wsl.exe",
    shellArgs: ["bash", "--login"],
    cwdStrategy: "home",
    envPolicy: {
      inheritSafeEnv: true,
      allowedEnvKeys: ["USERPROFILE", "HOME", "PATH", "TEMP", "TMP", "TERM"],
      blockedEnvKeys: ["GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
      injectProjectEnv: false,
    },
    safety: {
      readOnlyMode: false,
      allowDestructiveCommands: true,
      requireConfirmationForDangerousCommands: true,
      allowNetworkCommands: true,
      allowPackageInstall: true,
      allowVpnCommands: false,
    },
    aiAssist: { enabled: true, allowCommandSuggestions: true, allowCommandExplanation: true, allowAutoFixSuggestions: true, autoExecuteAllowed: false },
    productionReady: true,
  }),
  createProfile({
    id: "steamos-bash",
    name: "SteamOS Bash",
    description: "Default Steam Deck shell with project-aware workspace launch.",
    platform: "steamdeck",
    shellPath: "/bin/bash",
    shellArgs: ["--login"],
    cwdStrategy: "workspaceRoot",
    envPolicy: {
      inheritSafeEnv: true,
      allowedEnvKeys: ["HOME", "PATH", "TERM", "LANG", "LC_ALL", "DISPLAY", "XDG_RUNTIME_DIR"],
      blockedEnvKeys: ["GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
      injectProjectEnv: true,
    },
    safety: {
      readOnlyMode: false,
      allowDestructiveCommands: true,
      requireConfirmationForDangerousCommands: true,
      allowNetworkCommands: true,
      allowPackageInstall: true,
      allowVpnCommands: true,
    },
    aiAssist: { enabled: true, allowCommandSuggestions: true, allowCommandExplanation: true, allowAutoFixSuggestions: true, autoExecuteAllowed: false },
    productionReady: true,
  }),
  createProfile({
    id: "steamos-zsh",
    name: "SteamOS Zsh",
    description: "Steam Deck Zsh profile for users with custom shell setups.",
    platform: "steamdeck",
    shellPath: "/bin/zsh",
    shellArgs: ["--login"],
    cwdStrategy: "workspaceRoot",
    envPolicy: {
      inheritSafeEnv: true,
      allowedEnvKeys: ["HOME", "PATH", "TERM", "LANG", "LC_ALL", "DISPLAY", "XDG_RUNTIME_DIR"],
      blockedEnvKeys: ["GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
      injectProjectEnv: true,
    },
    safety: {
      readOnlyMode: false,
      allowDestructiveCommands: true,
      requireConfirmationForDangerousCommands: true,
      allowNetworkCommands: true,
      allowPackageInstall: true,
      allowVpnCommands: true,
    },
    aiAssist: { enabled: true, allowCommandSuggestions: true, allowCommandExplanation: true, allowAutoFixSuggestions: true, autoExecuteAllowed: false },
    productionReady: true,
  }),
  createProfile({
    id: "linux-sh",
    name: "Linux Sh",
    description: "Portable POSIX shell for recovery and low-assumption workflows.",
    platform: "linux",
    shellPath: "/bin/sh",
    shellArgs: [],
    cwdStrategy: "home",
    envPolicy: {
      inheritSafeEnv: true,
      allowedEnvKeys: ["HOME", "PATH", "TERM", "LANG", "LC_ALL"],
      blockedEnvKeys: ["GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
      injectProjectEnv: false,
    },
    safety: {
      readOnlyMode: true,
      allowDestructiveCommands: false,
      requireConfirmationForDangerousCommands: true,
      allowNetworkCommands: false,
      allowPackageInstall: false,
      allowVpnCommands: false,
    },
    aiAssist: { enabled: true, allowCommandSuggestions: true, allowCommandExplanation: true, allowAutoFixSuggestions: false, autoExecuteAllowed: false },
    productionReady: true,
  }),
  createProfile({
    id: "power-shell",
    name: "PowerShell",
    description: "Windows desktop shell profile with explicit confirmation gates.",
    platform: "windows",
    shellPath: "powershell.exe",
    shellArgs: ["-NoLogo"],
    cwdStrategy: "home",
    envPolicy: {
      inheritSafeEnv: true,
      allowedEnvKeys: ["USERPROFILE", "PATH", "TEMP", "TMP", "TERM"],
      blockedEnvKeys: ["GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
      injectProjectEnv: true,
    },
    safety: {
      readOnlyMode: false,
      allowDestructiveCommands: true,
      requireConfirmationForDangerousCommands: true,
      allowNetworkCommands: true,
      allowPackageInstall: true,
      allowVpnCommands: true,
    },
    aiAssist: { enabled: true, allowCommandSuggestions: true, allowCommandExplanation: true, allowAutoFixSuggestions: true, autoExecuteAllowed: false },
    productionReady: true,
  }),
  createProfile({
    id: "power-shell-core",
    name: "PowerShell Core",
    description: "Cross-platform PowerShell profile for modern automation flows.",
    platform: "windows",
    shellPath: "pwsh",
    shellArgs: ["-NoLogo"],
    cwdStrategy: "workspaceRoot",
    envPolicy: {
      inheritSafeEnv: true,
      allowedEnvKeys: ["USERPROFILE", "HOME", "PATH", "TEMP", "TMP", "TERM"],
      blockedEnvKeys: ["GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
      injectProjectEnv: true,
    },
    safety: {
      readOnlyMode: false,
      allowDestructiveCommands: true,
      requireConfirmationForDangerousCommands: true,
      allowNetworkCommands: true,
      allowPackageInstall: true,
      allowVpnCommands: true,
    },
    aiAssist: { enabled: true, allowCommandSuggestions: true, allowCommandExplanation: true, allowAutoFixSuggestions: true, autoExecuteAllowed: false },
    productionReady: true,
  }),
  createProfile({
    id: "windows-cmd",
    name: "Windows CMD",
    description: "Minimal Windows command prompt profile for compatibility work.",
    platform: "windows",
    shellPath: "cmd.exe",
    shellArgs: ["/Q"],
    cwdStrategy: "workspaceRoot",
    envPolicy: {
      inheritSafeEnv: true,
      allowedEnvKeys: ["USERPROFILE", "PATH", "TEMP", "TMP", "TERM"],
      blockedEnvKeys: ["GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
      injectProjectEnv: true,
    },
    safety: {
      readOnlyMode: false,
      allowDestructiveCommands: true,
      requireConfirmationForDangerousCommands: true,
      allowNetworkCommands: true,
      allowPackageInstall: true,
      allowVpnCommands: false,
    },
    aiAssist: { enabled: true, allowCommandSuggestions: true, allowCommandExplanation: true, allowAutoFixSuggestions: true, autoExecuteAllowed: false },
    productionReady: true,
  }),
  createProfile({
    id: "git-bash",
    name: "Git Bash",
    description: "Git for Windows Bash profile for Unix-oriented workflows.",
    platform: "windows",
    shellPath: "bash.exe",
    shellArgs: ["--login", "-i"],
    cwdStrategy: "workspaceRoot",
    envPolicy: {
      inheritSafeEnv: true,
      allowedEnvKeys: ["USERPROFILE", "HOME", "PATH", "TEMP", "TMP", "TERM"],
      blockedEnvKeys: ["GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
      injectProjectEnv: true,
    },
    safety: {
      readOnlyMode: false,
      allowDestructiveCommands: true,
      requireConfirmationForDangerousCommands: true,
      allowNetworkCommands: true,
      allowPackageInstall: true,
      allowVpnCommands: true,
    },
    aiAssist: { enabled: true, allowCommandSuggestions: true, allowCommandExplanation: true, allowAutoFixSuggestions: true, autoExecuteAllowed: false },
    productionReady: true,
  }),
  createProfile({
    id: "developer-shell",
    name: "Developer Shell",
    description: "General-purpose development profile with workspace env injection.",
    platform: "cross_platform",
    shellPath: "/bin/bash",
    shellArgs: ["--login"],
    cwdStrategy: "workspaceRoot",
    envPolicy: {
      inheritSafeEnv: true,
      allowedEnvKeys: ["HOME", "USERPROFILE", "PATH", "TERM", "LANG", "LC_ALL", "TMP", "TEMP"],
      blockedEnvKeys: ["GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
      injectProjectEnv: true,
    },
    safety: {
      readOnlyMode: false,
      allowDestructiveCommands: true,
      requireConfirmationForDangerousCommands: true,
      allowNetworkCommands: true,
      allowPackageInstall: true,
      allowVpnCommands: true,
    },
    aiAssist: { enabled: true, allowCommandSuggestions: true, allowCommandExplanation: true, allowAutoFixSuggestions: true, autoExecuteAllowed: false },
    productionReady: true,
  }),
  createProfile({
    id: "project-shell",
    name: "Project Shell",
    description: "Launches in the active project root for repo-local commands.",
    platform: "cross_platform",
    shellPath: "/bin/bash",
    shellArgs: ["--login"],
    cwdStrategy: "projectRoot",
    envPolicy: {
      inheritSafeEnv: true,
      allowedEnvKeys: ["HOME", "USERPROFILE", "PATH", "TERM", "LANG", "LC_ALL", "TMP", "TEMP"],
      blockedEnvKeys: ["GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
      injectProjectEnv: true,
    },
    safety: {
      readOnlyMode: false,
      allowDestructiveCommands: true,
      requireConfirmationForDangerousCommands: true,
      allowNetworkCommands: true,
      allowPackageInstall: true,
      allowVpnCommands: true,
    },
    aiAssist: { enabled: true, allowCommandSuggestions: true, allowCommandExplanation: true, allowAutoFixSuggestions: true, autoExecuteAllowed: false },
    productionReady: true,
  }),
  createProfile({
    id: "python-env-shell",
    name: "Python Env Shell",
    description: "Project-root shell intended for Python virtualenv and test flows.",
    platform: "cross_platform",
    shellPath: "/bin/bash",
    shellArgs: ["--login"],
    cwdStrategy: "projectRoot",
    envPolicy: {
      inheritSafeEnv: true,
      allowedEnvKeys: ["HOME", "USERPROFILE", "PATH", "TERM", "LANG", "LC_ALL", "VIRTUAL_ENV", "PYTHONPATH"],
      blockedEnvKeys: ["GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
      injectProjectEnv: true,
    },
    safety: {
      readOnlyMode: false,
      allowDestructiveCommands: true,
      requireConfirmationForDangerousCommands: true,
      allowNetworkCommands: true,
      allowPackageInstall: true,
      allowVpnCommands: false,
    },
    aiAssist: { enabled: true, allowCommandSuggestions: true, allowCommandExplanation: true, allowAutoFixSuggestions: true, autoExecuteAllowed: false },
    productionReady: true,
  }),
  createProfile({
    id: "node-project-shell",
    name: "Node Project Shell",
    description: "Project-root shell tuned for npm, pnpm, yarn, and bun workflows.",
    platform: "cross_platform",
    shellPath: "/bin/bash",
    shellArgs: ["--login"],
    cwdStrategy: "projectRoot",
    envPolicy: {
      inheritSafeEnv: true,
      allowedEnvKeys: ["HOME", "USERPROFILE", "PATH", "TERM", "LANG", "LC_ALL", "NODE_ENV", "NPM_CONFIG_CACHE", "PNPM_HOME"],
      blockedEnvKeys: ["GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
      injectProjectEnv: true,
    },
    safety: {
      readOnlyMode: false,
      allowDestructiveCommands: true,
      requireConfirmationForDangerousCommands: true,
      allowNetworkCommands: true,
      allowPackageInstall: true,
      allowVpnCommands: false,
    },
    aiAssist: { enabled: true, allowCommandSuggestions: true, allowCommandExplanation: true, allowAutoFixSuggestions: true, autoExecuteAllowed: false },
    productionReady: true,
  }),
  createProfile({
    id: "rust-project-shell",
    name: "Rust Project Shell",
    description: "Project-root shell for cargo, clippy, fmt, and test loops.",
    platform: "cross_platform",
    shellPath: "/bin/bash",
    shellArgs: ["--login"],
    cwdStrategy: "projectRoot",
    envPolicy: {
      inheritSafeEnv: true,
      allowedEnvKeys: ["HOME", "USERPROFILE", "PATH", "TERM", "LANG", "LC_ALL", "CARGO_HOME", "RUSTUP_HOME"],
      blockedEnvKeys: ["GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
      injectProjectEnv: true,
    },
    safety: {
      readOnlyMode: false,
      allowDestructiveCommands: true,
      requireConfirmationForDangerousCommands: true,
      allowNetworkCommands: true,
      allowPackageInstall: true,
      allowVpnCommands: false,
    },
    aiAssist: { enabled: true, allowCommandSuggestions: true, allowCommandExplanation: true, allowAutoFixSuggestions: true, autoExecuteAllowed: false },
    productionReady: true,
  }),
  createProfile({
    id: "go-project-shell",
    name: "Go Project Shell",
    description: "Project-root shell for go build, test, fmt, and module maintenance.",
    platform: "cross_platform",
    shellPath: "/bin/bash",
    shellArgs: ["--login"],
    cwdStrategy: "projectRoot",
    envPolicy: {
      inheritSafeEnv: true,
      allowedEnvKeys: ["HOME", "USERPROFILE", "PATH", "TERM", "LANG", "LC_ALL", "GOPATH", "GOMODCACHE"],
      blockedEnvKeys: ["GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
      injectProjectEnv: true,
    },
    safety: {
      readOnlyMode: false,
      allowDestructiveCommands: true,
      requireConfirmationForDangerousCommands: true,
      allowNetworkCommands: true,
      allowPackageInstall: true,
      allowVpnCommands: false,
    },
    aiAssist: { enabled: true, allowCommandSuggestions: true, allowCommandExplanation: true, allowAutoFixSuggestions: true, autoExecuteAllowed: false },
    productionReady: true,
  }),
  createProfile({
    id: "lua-hermes-shell",
    name: "Lua/Hermes Shell",
    description: "Plugin and Lua automation shell for validation and repair flows.",
    platform: "cross_platform",
    shellPath: "/bin/bash",
    shellArgs: ["--login"],
    cwdStrategy: "workspaceRoot",
    envPolicy: {
      inheritSafeEnv: true,
      allowedEnvKeys: ["HOME", "USERPROFILE", "PATH", "TERM", "LANG", "LC_ALL"],
      blockedEnvKeys: ["GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
      injectProjectEnv: true,
    },
    safety: {
      readOnlyMode: false,
      allowDestructiveCommands: true,
      requireConfirmationForDangerousCommands: true,
      allowNetworkCommands: true,
      allowPackageInstall: false,
      allowVpnCommands: false,
    },
    aiAssist: { enabled: true, allowCommandSuggestions: true, allowCommandExplanation: true, allowAutoFixSuggestions: true, autoExecuteAllowed: false },
    productionReady: true,
  }),
  createProfile({
    id: "security-tools-shell",
    name: "Security Tools Shell",
    description: "Auditing profile for diagnostics, scanning, and hardened inspection tasks.",
    platform: "cross_platform",
    shellPath: "/bin/bash",
    shellArgs: ["--login"],
    cwdStrategy: "workspaceRoot",
    envPolicy: {
      inheritSafeEnv: true,
      allowedEnvKeys: ["HOME", "USERPROFILE", "PATH", "TERM", "LANG", "LC_ALL"],
      blockedEnvKeys: ["GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
      injectProjectEnv: false,
    },
    safety: {
      readOnlyMode: false,
      allowDestructiveCommands: false,
      requireConfirmationForDangerousCommands: true,
      allowNetworkCommands: true,
      allowPackageInstall: false,
      allowVpnCommands: true,
    },
    aiAssist: { enabled: true, allowCommandSuggestions: true, allowCommandExplanation: true, allowAutoFixSuggestions: false, autoExecuteAllowed: false },
    productionReady: true,
  }),
  createProfile({
    id: "vpn-network-tools-shell",
    name: "VPN/Network Tools Shell",
    description: "Networking profile for route checks, proxy diagnostics, and VPN verification.",
    platform: "cross_platform",
    shellPath: "/bin/bash",
    shellArgs: ["--login"],
    cwdStrategy: "workspaceRoot",
    envPolicy: {
      inheritSafeEnv: true,
      allowedEnvKeys: ["HOME", "USERPROFILE", "PATH", "TERM", "LANG", "LC_ALL"],
      blockedEnvKeys: ["GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
      injectProjectEnv: false,
    },
    safety: {
      readOnlyMode: false,
      allowDestructiveCommands: false,
      requireConfirmationForDangerousCommands: true,
      allowNetworkCommands: true,
      allowPackageInstall: false,
      allowVpnCommands: true,
    },
    aiAssist: { enabled: true, allowCommandSuggestions: true, allowCommandExplanation: true, allowAutoFixSuggestions: false, autoExecuteAllowed: false },
    productionReady: true,
  }),
  createProfile({
    id: "read-only-safe-shell",
    name: "Read-Only Safe Shell",
    description: "Conservative shell profile for diagnostics and inspection only.",
    platform: "cross_platform",
    shellPath: "/bin/sh",
    shellArgs: [],
    cwdStrategy: "workspaceRoot",
    envPolicy: {
      inheritSafeEnv: true,
      allowedEnvKeys: ["HOME", "PATH", "TERM", "LANG", "LC_ALL"],
      blockedEnvKeys: ["GEMINI_API_KEY", "OPENAI_API_KEY", "ANTHROPIC_API_KEY"],
      injectProjectEnv: false,
    },
    safety: {
      readOnlyMode: true,
      allowDestructiveCommands: false,
      requireConfirmationForDangerousCommands: true,
      allowNetworkCommands: false,
      allowPackageInstall: false,
      allowVpnCommands: false,
    },
    aiAssist: { enabled: true, allowCommandSuggestions: true, allowCommandExplanation: true, allowAutoFixSuggestions: false, autoExecuteAllowed: false },
    productionReady: true,
  }),
];
