export const state = {
    currentSessionId: "",
    activePersona: "Default",
    availablePersonas: [],
    isMuted: localStorage.getItem("isMuted") === "true",
    isProcessRunning: false,
    terminalSessions: [],
    activeTerminalSessionId: null,
    ptySessionId: null,
    sshSessionId: null,
    ftpCurrentPath: "/",
    sftpCurrentPath: "/",
    isRecording: false,
    notifications: [],
    unreadNotifCount: 0,
    currentAIMessage: null,
    currentAIText: "",
    activeTerminalBody: null,
    activeExecuteBtn: null,
    pendingLuaScript: "",
    streamStartTime: 0,
    firstChunkTime: 0,
    totalTokens: 0,
    radialMenuVisible: false,
    gamepadActive: false,
    gamepadFocusIndex: -1,
    previousGamepadState: { buttons: [] },
    tpCursorX: 640,
    tpCursorY: 400,
    tpCursorVisible: false,
    tpCursorHideTimer: null,
    tpScrollVisible: false,
    tpScrollHideTimer: null,
    radialSelectedSegment: null,
    activeProvider: "gemini",
    tunnelStatus: "offline",
    selectedPeerIp: null,
    pendingTransferId: null
};
