const fs = require('fs');
const src = fs.readFileSync('frontend/src/main.js', 'utf8');
const lines = src.split('\n');

// lines 7175-7604 (1-indexed) = indices 7174-7603 (0-indexed)
const before = lines.slice(0, 7174);
const after = lines.slice(7604);

const replacement = [
`function _browserParseUrlOrSearch(input) {`,
`  const trimmed = input.trim();`,
`  if (!trimmed) return "neurodeck://home";`,
`  if (/^[a-zA-Z0-9+.-]+:\\/\\//.test(trimmed)) return trimmed;`,
`  const isDomain =`,
`    /^[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}(:\\d+)?(\\/.*)?$/.test(trimmed) ||`,
`    /^localhost(:\\d+)?(\\/.*)?$/.test(trimmed) ||`,
`    /^\\d{1,3}(\\.\\d{1,3}){3}(:\\d+)?(\\/.*)?$/.test(trimmed);`,
`  return isDomain ? "https://" + trimmed : "https://html.duckduckgo.com/html/?q=" + encodeURIComponent(trimmed);`,
`}`,
``,
`// Returns the browser viewport area in logical CSS pixels, viewport-relative.`,
`// The native browser window is positioned by Rust using viewport coords + Tauri inner_position().`,
`function _browserGetViewportRect() {`,
`  const view = document.getElementById("view-browser");`,
`  if (!view) return null;`,
`  const toolbar = view.querySelector(".browser-toolbar");`,
`  const toolbarH = toolbar ? toolbar.getBoundingClientRect().height : 52;`,
`  const r = view.getBoundingClientRect();`,
`  return { x: r.left, y: r.top + toolbarH, width: r.width, height: r.height - toolbarH };`,
`}`,
``,
`function _browserRectsEqual(a, b) {`,
`  return a && b && a.x === b.x && a.y === b.y && a.width === b.width && a.height === b.height;`,
`}`,
``,
`async function _browserNavigateTo(raw, bCtx, urlInput, homeScreen) {`,
`  const url = _browserParseUrlOrSearch(raw);`,
`  if (url === "neurodeck://home") {`,
`    bCtx.url = "neurodeck://home";`,
`    if (bCtx.open) await invoke("browser_hide").catch(() => {});`,
`    if (homeScreen) homeScreen.classList.remove("hidden");`,
`    if (urlInput) urlInput.value = "";`,
`    return;`,
`  }`,
`  bCtx.url = url;`,
`  if (urlInput) urlInput.value = url;`,
`  const r = _browserGetViewportRect();`,
`  if (!r) return;`,
`  try {`,
`    if (bCtx.open) {`,
`      await invoke("browser_navigate", { url });`,
`    } else {`,
`      await invoke("browser_open", { url, viewportX: r.x, viewportY: r.y, width: r.width, height: r.height });`,
`      bCtx.open = true;`,
`      if (homeScreen) homeScreen.classList.add("hidden");`,
`    }`,
`  } catch (e) {`,
`    console.error("[Browser] Navigation error:", e);`,
`    window.addNotification("Browser Error", String(e), "error");`,
`  }`,
`}`,
``,
`function _browserStartSync(urlInput, bCtx) {`,
`  if (bCtx.syncInt) return;`,
`  bCtx.syncInt = setInterval(async () => {`,
`    if (!bCtx.open) return;`,
`    const r = _browserGetViewportRect();`,
`    if (r && !_browserRectsEqual(r, bCtx.lastRect)) {`,
`      bCtx.lastRect = r;`,
`      await invoke("browser_show", { viewportX: r.x, viewportY: r.y, width: r.width, height: r.height }).catch(() => {});`,
`    }`,
`    try {`,
`      const liveUrl = await invoke("browser_get_url");`,
`      if (liveUrl && liveUrl !== bCtx.url && document.activeElement !== urlInput) {`,
`        bCtx.url = liveUrl;`,
`        if (urlInput) urlInput.value = liveUrl;`,
`      }`,
`      const downloadModelBtn = document.getElementById("browser-download-model-btn");`,
`      if (downloadModelBtn) {`,
`        const match = liveUrl ? liveUrl.match(/huggingface\\.co\\/([^/]+)\\/([^/?#]+)/) : null;`,
`        if (match) {`,
`          const org = match[1];`,
`          const model = match[2];`,
`          if (!["datasets", "spaces", "docs", "blog"].includes(org)) {`,
`            downloadModelBtn.disabled = false;`,
`            downloadModelBtn.dataset.repo = org + "/" + model;`,
`          } else {`,
`            downloadModelBtn.disabled = true;`,
`            delete downloadModelBtn.dataset.repo;`,
`          }`,
`        } else {`,
`          downloadModelBtn.disabled = true;`,
`          delete downloadModelBtn.dataset.repo;`,
`        }`,
`      }`,
`    } catch (_) {}`,
`  }, 250);`,
`}`,
``,
`function _browserStopSync(bCtx) {`,
`  if (bCtx.syncInt) { clearInterval(bCtx.syncInt); bCtx.syncInt = null; }`,
`  bCtx.lastRect = null;`,
`}`,
``,
`function _browserWireTabViz(browserTab, bCtx, urlInput, homeScreen) {`,
`  if (browserTab) {`,
`    browserTab.addEventListener("click", async () => {`,
`      if (bCtx.open && bCtx.url !== "neurodeck://home") {`,
`        const r = _browserGetViewportRect();`,
`        if (r) await invoke("browser_show", { viewportX: r.x, viewportY: r.y, width: r.width, height: r.height }).catch(() => {});`,
`      }`,
`      _browserStartSync(urlInput, bCtx);`,
`    });`,
`  }`,
`  document.querySelectorAll('.nav-tab:not([data-view="browser"])').forEach((tab) => {`,
`    tab.addEventListener("click", () => {`,
`      if (bCtx.open) invoke("browser_hide").catch(() => {});`,
`      _browserStopSync(bCtx);`,
`    });`,
`  });`,
`}`,
``,
`function _browserWireNavBtns(els, bCtx, urlInput, homeScreen) {`,
`  const { backBtn, forwardBtn, refreshBtn, homeBtn, hfBtn, goBtn, clearBtn, openExtBtn } = els;`,
`  if (goBtn && urlInput) {`,
`    goBtn.onclick = () => _browserNavigateTo(urlInput.value, bCtx, urlInput, homeScreen);`,
`    urlInput.addEventListener("keydown", (e) => { if (e.key === "Enter") _browserNavigateTo(urlInput.value, bCtx, urlInput, homeScreen); });`,
`  }`,
`  if (clearBtn && urlInput) { clearBtn.onclick = () => { urlInput.value = ""; urlInput.focus(); }; }`,
`  if (backBtn) backBtn.onclick = () => { if (bCtx.open) invoke("browser_exec", { js: "window.history.back()" }).catch(() => {}); };`,
`  if (forwardBtn) forwardBtn.onclick = () => { if (bCtx.open) invoke("browser_exec", { js: "window.history.forward()" }).catch(() => {}); };`,
`  if (refreshBtn) refreshBtn.onclick = () => { if (bCtx.open) invoke("browser_exec", { js: "window.location.reload()" }).catch(() => {}); };`,
`  if (homeBtn) homeBtn.onclick = () => _browserNavigateTo("neurodeck://home", bCtx, urlInput, homeScreen);`,
`  if (hfBtn) hfBtn.onclick = () => _browserNavigateTo("https://huggingface.co/models", bCtx, urlInput, homeScreen);`,
`  if (openExtBtn) {`,
`    openExtBtn.onclick = () => {`,
`      const url = urlInput ? urlInput.value.trim() : bCtx.url;`,
`      const parsed = _browserParseUrlOrSearch(url || bCtx.url);`,
`      if (parsed && parsed !== "neurodeck://home") invoke("open_external", { url: parsed }).catch(() => {});`,
`    };`,
`  }`,
`}`,
``,
`function _browserWireSaveMemory(btn, urlInput, bCtx) {`,
`  if (!btn) return;`,
`  btn.onclick = async () => {`,
`    const url = (urlInput ? urlInput.value.trim() : null) || bCtx.url;`,
`    const parsed = _browserParseUrlOrSearch(url);`,
`    if (!parsed || parsed === "neurodeck://home") return;`,
`    btn.disabled = true;`,
`    const originalHtml = btn.innerHTML;`,
`    btn.innerHTML = createIcon("database", { size: 14 }) + "<span>Saving...</span>";`,
`    try {`,
`      const res = await invoke("browser_save_to_memory", { url: parsed });`,
`      btn.innerHTML = createIcon("check", { size: 14 }) + "<span>Saved (" + res.indexed + " chunks)</span>";`,
`      setTimeout(() => { btn.disabled = false; btn.innerHTML = originalHtml; }, 3000);`,
`    } catch (e) {`,
`      console.error("Save memory error:", e);`,
`      btn.innerHTML = createIcon("x", { size: 14 }) + "<span>Failed</span>";`,
`      setTimeout(() => { btn.disabled = false; btn.innerHTML = originalHtml; }, 3000);`,
`    }`,
`  };`,
`}`,
``,
`function _browserWireCopyCitation(btn, urlInput, bCtx) {`,
`  if (!btn) return;`,
`  btn.onclick = async () => {`,
`    const url = (urlInput ? urlInput.value.trim() : null) || bCtx.url;`,
`    const parsed = _browserParseUrlOrSearch(url);`,
`    if (!parsed || parsed === "neurodeck://home") return;`,
`    btn.disabled = true;`,
`    const originalHtml = btn.innerHTML;`,
`    btn.innerHTML = createIcon("quote", { size: 14 }) + "<span>Fetching...</span>";`,
`    try {`,
`      const citation = await invoke("browser_get_citation", { url: parsed });`,
`      await navigator.clipboard.writeText(citation);`,
`      btn.innerHTML = createIcon("check", { size: 14 }) + "<span>Copied</span>";`,
`      setTimeout(() => { btn.disabled = false; btn.innerHTML = originalHtml; }, 2000);`,
`    } catch (e) {`,
`      console.error("Copy citation error:", e);`,
`      btn.innerHTML = createIcon("x", { size: 14 }) + "<span>Failed</span>";`,
`      setTimeout(() => { btn.disabled = false; btn.innerHTML = originalHtml; }, 2000);`,
`    }`,
`  };`,
`}`,
``,
`function _browserWireDownloadModel(btn, bCtx) {`,
`  if (!btn) return;`,
`  btn.onclick = () => {`,
`    const repo = btn.dataset.repo;`,
`    if (!repo) return;`,
`    btn.disabled = true;`,
`    const btnSpan = btn.querySelector("span");`,
`    const originalText = btnSpan ? btnSpan.textContent : "Download Model";`,
`    if (btnSpan) btnSpan.textContent = "Checking...";`,
`    const proceedToModelSearch = () => {`,
`      if (bCtx.open) invoke("browser_hide").catch(() => {});`,
`      _browserStopSync(bCtx);`,
`      openSettingsModal();`,
`      activateSettingsPanel("sp-models", "models");`,
`      switchToBrowseTabAndSearch(repo);`,
`      if (btnSpan) btnSpan.textContent = originalText;`,
`      btn.disabled = false;`,
`    };`,
`    invoke("hf_get_model_info", { repoId: repo })`,
`      .then((modelInfo) => {`,
`        if (!modelInfo.steam_deck_compat) {`,
`          const ok = window.confirm(`,
`            "\\u26A0\\uFE0F Compatibility Warning\\n\\nThe model \\"" + repo + "\\" might not run flawlessly on the Steam Deck.\\n" +`,
`            "\\u2022 Steam Deck has 16GB of unified RAM.\\n\\u2022 Flawlessly compatible models are usually < 6GB in size and <= 7B parameters.\\n\\n" +`,
`            "Do you still want to proceed with downloading it?"`,
`          );`,
`          if (!ok) { if (btnSpan) btnSpan.textContent = originalText; btn.disabled = false; return; }`,
`        }`,
`        proceedToModelSearch();`,
`      })`,
`      .catch((err) => {`,
`        const ok = window.confirm(`,
`          "\\u26A0\\uFE0F Compatibility Check Failed\\n\\nCould not verify Steam Deck compatibility for \\"" + repo + "\\" (Error: " + err + ").\\n\\n" +`,
`          "Do you still want to proceed to the Model Library?"`,
`        );`,
`        if (!ok) { if (btnSpan) btnSpan.textContent = originalText; btn.disabled = false; return; }`,
`        proceedToModelSearch();`,
`      });`,
`  };`,
`}`,
``,
`function _browserWireSpeedDial(cards, bCtx, urlInput, homeScreen) {`,
`  cards.forEach((card) => {`,
`    card.onclick = () => { const url = card.getAttribute("data-url"); if (url) _browserNavigateTo(url, bCtx, urlInput, homeScreen); };`,
`  });`,
`}`,
``,
`function _browserWireHomeSearch(btn, input, bCtx, urlInput, homeScreen) {`,
`  if (!btn || !input) return;`,
`  btn.onclick = () => { const q = input.value.trim(); if (q) _browserNavigateTo(q, bCtx, urlInput, homeScreen); };`,
`  input.addEventListener("keydown", (e) => { if (e.key === "Enter") { const q = input.value.trim(); if (q) _browserNavigateTo(q, bCtx, urlInput, homeScreen); } });`,
`}`,
``,
`function _browserWireKeyboard(els, bCtx, urlInput) {`,
`  const { refreshBtn, backBtn, forwardBtn } = els;`,
`  document.addEventListener("keydown", (e) => {`,
`    const bv = document.getElementById("view-browser");`,
`    if (!bv || !bv.classList.contains("active")) return;`,
`    if (e.key === "F5") { e.preventDefault(); if (refreshBtn) refreshBtn.click(); }`,
`    if ((e.ctrlKey || e.metaKey) && e.key === "l") { e.preventDefault(); if (urlInput) { urlInput.focus(); urlInput.select(); } }`,
`    if (e.altKey && e.key === "ArrowLeft") { e.preventDefault(); if (backBtn) backBtn.click(); }`,
`    if (e.altKey && e.key === "ArrowRight") { e.preventDefault(); if (forwardBtn) forwardBtn.click(); }`,
`  });`,
`}`,
``,
`function initBrowser() {`,
`  const urlInput = document.getElementById("browser-url-input");`,
`  const clearBtn = document.getElementById("browser-url-clear-btn");`,
`  const goBtn = document.getElementById("browser-go-btn");`,
`  const openExtBtn = document.getElementById("browser-open-ext-btn");`,
`  const homeScreen = document.getElementById("browser-home-screen");`,
`  const backBtn = document.getElementById("browser-back-btn");`,
`  const forwardBtn = document.getElementById("browser-forward-btn");`,
`  const refreshBtn = document.getElementById("browser-refresh-btn");`,
`  const homeBtn = document.getElementById("browser-home-btn");`,
`  const hfBtn = document.getElementById("browser-hf-btn");`,
`  const homeSearchInput = document.getElementById("browser-home-search-input");`,
`  const homeSearchBtn = document.getElementById("browser-home-search-btn");`,
`  const saveMemoryBtn = document.getElementById("browser-save-memory-btn");`,
`  const copyCitationBtn = document.getElementById("browser-copy-citation-btn");`,
`  const speedDialCards = document.querySelectorAll(".speed-dial-card");`,
`  const downloadModelBtn = document.getElementById("browser-download-model-btn");`,
`  const browserTab = document.querySelector('.nav-tab[data-view="browser"]');`,
``,
`  const oldIframe = document.getElementById("browser-iframe");`,
`  if (oldIframe) oldIframe.style.display = "none";`,
`  const blockedScreen = document.getElementById("browser-blocked-screen");`,
`  if (blockedScreen) blockedScreen.style.display = "none";`,
``,
`  const bCtx = { open: false, url: "neurodeck://home", syncInt: null, lastRect: null };`,
`  window.browserNavigateTo = (raw) => _browserNavigateTo(raw, bCtx, urlInput, homeScreen);`,
``,
`  _browserWireTabViz(browserTab, bCtx, urlInput, homeScreen);`,
`  _browserWireNavBtns({ backBtn, forwardBtn, refreshBtn, homeBtn, hfBtn, goBtn, clearBtn, openExtBtn }, bCtx, urlInput, homeScreen);`,
`  _browserWireSaveMemory(saveMemoryBtn, urlInput, bCtx);`,
`  _browserWireCopyCitation(copyCitationBtn, urlInput, bCtx);`,
`  _browserWireDownloadModel(downloadModelBtn, bCtx);`,
`  _browserWireSpeedDial(speedDialCards, bCtx, urlInput, homeScreen);`,
`  _browserWireHomeSearch(homeSearchBtn, homeSearchInput, bCtx, urlInput, homeScreen);`,
`  _browserWireKeyboard({ refreshBtn, backBtn, forwardBtn }, bCtx, urlInput);`,
`}`,
].join('\n');

const result = [...before, replacement, ...after].join('\n');
fs.writeFileSync('frontend/src/main.js', result);
console.log('Done. Total lines:', result.split('\n').length);
